SELECT DISTINCT
    CODIGO_CLIENTE,
    HORARIO_CLIENTE,
    T_CIUDAD_A,
    T_CIUDAD_B,
    T_CIUDAD_C,
    TOTAL_PAGADO_CIUDAD_B,
    MONTO_MENOR_C,
    MONTO_MAYOR_A,
    TOTAL_PAGADO_CIUDAD_B-MONTO_MENOR_B DIFERENCIA_B,
    RANKING,
    DENSE_RANKING,
    ROUND(PORCENTAJE_CIUDAD_A,2)PORCENTAJE_CIUDAD_A,
    ROUND(PORCENTAJE_CIUDAD_B,2)PORCENTAJE_CIUDAD_B,
    ROUND(PORCENTAJE_CIUDAD_C,2)PORCENTAJE_CIUDAD_C,
    ROUND(PROMEDIO_PAGADO_CLIENTE,2)PROMEDIO_PAGADO_CLIENTE,
    ROUND(PROMEDIO_PAGADO_CLIENTE * TOTAL_RESERVAS, 2) PROMEDIO_PAGADO_TOTAL_RESERVAS,
    HORARIOS_UTILIZADOS
FROM (
    SELECT
        CODIGO_CLIENTE,
        HORARIO_CLIENTE,
        T_CIUDAD_A,
        T_CIUDAD_B,
        T_CIUDAD_C,
        T_CLIENTE,
        TOTAL_PAGADO_CIUDAD_B,
        AVG((T_CIUDAD_A/ T_CLIENTE) * 100) OVER (PARTITION BY CODIGO_CLIENTE) PORCENTAJE_CIUDAD_A,
        AVG((T_CIUDAD_B/ T_CLIENTE) * 100) OVER (PARTITION BY CODIGO_CLIENTE) PORCENTAJE_CIUDAD_B,
        AVG((T_CIUDAD_C/ T_CLIENTE) * 100) OVER (PARTITION BY CODIGO_CLIENTE) PORCENTAJE_CIUDAD_C,
        AVG(T_CLIENTE/ 3) OVER (ORDER BY CODIGO_CLIENTE) PROMEDIO_PAGADO_CLIENTE,
        RANK() OVER (ORDER BY T_CLIENTE) RANKING,
        DENSE_RANK() OVER (ORDER BY T_CLIENTE) DENSE_RANKING,
        FIRST_VALUE(T_CIUDAD_C) OVER (ORDER BY T_CIUDAD_C) MONTO_MENOR_C,
        FIRST_VALUE(T_CIUDAD_B) OVER (PARTITION BY CODIGO_CLIENTE ORDER BY T_CIUDAD_B) MONTO_MENOR_B,
        LAST_VALUE(T_CIUDAD_A) OVER (ORDER BY T_CIUDAD_A RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) MONTO_MAYOR_A,
        COUNT(T_CIUDAD_A) OVER(PARTITION BY CODIGO_CLIENTE)+
        COUNT(T_CIUDAD_B) OVER(PARTITION BY CODIGO_CLIENTE)+
        COUNT(T_CIUDAD_C) OVER(PARTITION BY CODIGO_CLIENTE) TOTAL_RESERVAS,
        LISTAGG(HORARIO_CLIENTE, ', ') WITHIN GROUP (ORDER BY HORARIO_CLIENTE) 
        OVER (PARTITION BY CODIGO_CLIENTE) HORARIOS_UTILIZADOS
    FROM(
        SELECT
            CODIGO_CLIENTE,
            HORARIO_CLIENTE,
            SUM(CIUDAD_A) OVER (PARTITION BY CODIGO_CLIENTE ORDER BY CODIGO_CLIENTE) T_CIUDAD_A,
            SUM(CIUDAD_B) OVER (PARTITION BY CODIGO_CLIENTE ORDER BY CODIGO_CLIENTE) T_CIUDAD_B,
            SUM(CIUDAD_C) OVER (PARTITION BY CODIGO_CLIENTE ORDER BY CODIGO_CLIENTE) T_CIUDAD_C,
            SUM(CIUDAD_B) OVER () TOTAL_PAGADO_CIUDAD_B,
            SUM(CIUDAD_A) OVER (PARTITION BY CODIGO_CLIENTE) +
            SUM(CIUDAD_B) OVER (PARTITION BY CODIGO_CLIENTE) +
            SUM(CIUDAD_C) OVER (PARTITION BY CODIGO_CLIENTE) T_CLIENTE
        FROM (
            SELECT
                CODIGO_CLIENTE,
                HORARIO HORARIO_CLIENTE,
                DESTINO DESTINO_CLIENTE,
                CANTIDAD_MENORES_18_NACIONALES,
                CANTIDAD_ADULTOS_NACIONALES,
                CANTIDAD_MENORES_18_TURISTAS,
                CANTIDAD_ADULTOS_TURISTAS,
                (COSTO_MENORES_18_NACIONALES * CANTIDAD_MENORES_18_NACIONALES +
                 COSTO_MENORES_18_TURISTAS * CANTIDAD_MENORES_18_TURISTAS +
                 COSTO_ADULTOS_NACIONALES * CANTIDAD_ADULTOS_NACIONALES +
                 COSTO_ADULTOS_TURISTAS * CANTIDAD_ADULTOS_TURISTAS) MONTO_TOTAL
            FROM AGENCIATURISMO
    )
            PIVOT (SUM(MONTO_TOTAL)
            FOR DESTINO_CLIENTE IN ('Ciudad A' CIUDAD_A, 'Ciudad B' CIUDAD_B, 'Ciudad C' CIUDAD_C)
        )
    )
)
ORDER BY CODIGO_CLIENTE;